### ISSUE TITLE
Change our manual SQL style to use an ORM instead

### ISSUE THREAD

**Issue by MarkusReynolds1989** [MarkusReynolds1989/BugTracker#4]
Install and use Entity Framework.

**Comment by aseemsahoo** [comment]
Dapper is a much faster ORM. Most likely would work better with your project.

**Comment by MarkusReynolds1989** [comment]
> Dapper is a much faster ORM. Most likely would work better with your project.

We will keep that in mind if anyone else goes back to update this project :)

**Comment by MarkusReynolds1989** [comment]
@aseemsahoo I'll go ahead and work on this.
